import React, { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'
import { saveFeedback } from '../utils/api'
import { Download, CheckCircle, AlertCircle, ChevronLeft } from 'lucide-react'
import jsPDF from 'jspdf'

const OUTCOMES = [
    { id: 'approved', label: '✅ Approved', color: 'green' },
    { id: 'partial', label: '🟡 Partially', color: 'amber' },
    { id: 'pending', label: '🕐 Pending', color: 'blue' },
    { id: 'rejected', label: '❌ Rejected', color: 'red' },
]

const BANKS = [
    'HDFC Bank', 'SBI', 'ICICI Bank', 'Axis Bank', 'Kotak Mahindra Bank',
    'Bank of Baroda', 'Punjab National Bank', 'IndusInd Bank', 'Yes Bank',
    'Bajaj Finance', 'IDFC First Bank', 'Federal Bank', 'Other',
]

export default function Feedback() {
    const { state } = useLocation()
    const navigate = useNavigate()
    const s = state || { sessionId: 'demo', loanType: 'personal', score: 68 }

    const [form, setForm] = useState({
        bankApplied: '',
        outcome: '',
        interestRate: '',
        approvedAmount: '',
    })
    const [submitted, setSubmitted] = useState(false)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState('')
    const setField = (k, v) => setForm(f => ({ ...f, [k]: v }))

    async function handleSubmit() {
        if (!form.bankApplied || !form.outcome) {
            setError('Please select a bank and an outcome.')
            return
        }
        setError('')
        setLoading(true)
        try {
            await saveFeedback({
                sessionId: s.sessionId,
                bankApplied: form.bankApplied,
                outcome: form.outcome,
                interestRate: form.interestRate || null,
                approvedAmount: form.approvedAmount || null,
            })
            setSubmitted(true)
        } catch (e) {
            setError('Failed to save feedback. Please try again.')
        } finally {
            setLoading(false)
        }
    }

    function downloadPDF() {
        const doc = new jsPDF()
        const gold = [201, 168, 76]
        const dark = [30, 30, 30]

        // Header
        doc.setFillColor(...gold)
        doc.rect(0, 0, 210, 30, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(20)
        doc.setFont('helvetica', 'bold')
        doc.text('Veritas AI — Eligibility Report', 15, 20)

        // Body
        doc.setTextColor(...dark)
        doc.setFontSize(12)
        doc.setFont('helvetica', 'normal')

        const lines = [
            ['Loan Type', s.loanType === 'personal' ? 'Personal Loan' : 'Business Loan'],
            ['Eligibility Score', `${s.score} / 100`],
            ['Bank Applied', form.bankApplied],
            ['Outcome', form.outcome.charAt(0).toUpperCase() + form.outcome.slice(1)],
            form.interestRate ? ['Interest Rate', `${form.interestRate}% p.a.`] : null,
            form.approvedAmount ? ['Amount Approved', `₹${Number(form.approvedAmount).toLocaleString('en-IN')}`] : null,
            ['Generated On', new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })],
        ].filter(Boolean)

        let y = 48
        lines.forEach(([label, value]) => {
            doc.setFont('helvetica', 'bold')
            doc.text(label + ':', 15, y)
            doc.setFont('helvetica', 'normal')
            doc.text(value, 80, y)
            doc.setDrawColor(230, 230, 220)
            doc.line(15, y + 3, 195, y + 3)
            y += 14
        })

        // Disclaimer
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text('This report is generated by Veritas AI for informational purposes only. Actual approval decisions rest with the lender.', 15, 270, { maxWidth: 180 })

        doc.save('uniloan-eligibility-report.pdf')
    }

    return (
        <div className="min-h-screen bg-cream flex flex-col">
            <Navbar />
            <main className="flex-1 max-w-lg mx-auto w-full px-4 sm:px-6 py-10 fade-in">
                <button
                    onClick={() => navigate(-1)}
                    className="flex items-center gap-1.5 text-sm text-gray-400 hover:text-gray-700 mb-6 transition-colors"
                >
                    <ChevronLeft size={16} /> Back to Results
                </button>

                {!submitted ? (
                    <>
                        <div className="mb-8">
                            <h1 className="section-title">Share Your Outcome</h1>
                            <p className="text-sm text-gray-500 mt-1">
                                Help improve our model — and unlock your <strong className="text-gold">free PDF report</strong> when you submit.
                            </p>
                        </div>

                        <div className="card space-y-5">
                            {/* Bank applied */}
                            <div>
                                <label className="label-base">Bank Applied To <span className="text-red-400">*</span></label>
                                <select
                                    id="feedback-bank"
                                    value={form.bankApplied}
                                    onChange={e => setField('bankApplied', e.target.value)}
                                    className="input-base"
                                >
                                    <option value="">Select bank…</option>
                                    {BANKS.map(b => <option key={b}>{b}</option>)}
                                </select>
                            </div>

                            {/* Outcome */}
                            <div>
                                <label className="label-base">Loan Outcome <span className="text-red-400">*</span></label>
                                <div className="grid grid-cols-2 gap-2 mt-1">
                                    {OUTCOMES.map(o => (
                                        <button
                                            key={o.id}
                                            id={`outcome-${o.id}`}
                                            onClick={() => setField('outcome', o.id)}
                                            className={`py-2.5 px-3 rounded-xl text-sm font-medium border transition-all duration-200 ${form.outcome === o.id
                                                    ? 'bg-gold text-white border-gold shadow-gold'
                                                    : 'bg-white text-gray-600 border-gray-200 hover:border-gold/50'
                                                }`}
                                        >
                                            {o.label}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            {/* Optional: interest rate */}
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="label-base">Interest Rate (% p.a.)</label>
                                    <input
                                        id="interest-rate"
                                        type="number"
                                        step="0.01"
                                        placeholder="e.g. 10.75"
                                        value={form.interestRate}
                                        onChange={e => setField('interestRate', e.target.value)}
                                        className="input-base"
                                    />
                                </div>
                                <div>
                                    <label className="label-base">Amount Approved (₹)</label>
                                    <input
                                        id="approved-amount"
                                        type="number"
                                        placeholder="e.g. 400000"
                                        value={form.approvedAmount}
                                        onChange={e => setField('approvedAmount', e.target.value)}
                                        className="input-base"
                                    />
                                </div>
                            </div>

                            {error && (
                                <div className="flex items-start gap-2 text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-4 py-3">
                                    <AlertCircle size={15} className="shrink-0 mt-0.5" />
                                    {error}
                                </div>
                            )}

                            <button
                                id="submit-feedback"
                                onClick={handleSubmit}
                                disabled={loading}
                                className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-60"
                            >
                                {loading ? 'Saving…' : 'Submit & Unlock PDF Report'}
                            </button>
                        </div>
                    </>
                ) : (
                    /* Success state */
                    <div className="card flex flex-col items-center text-center py-10 gap-5">
                        <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center">
                            <CheckCircle size={32} className="text-green-500" />
                        </div>
                        <div>
                            <h2 className="font-serif text-2xl text-gray-900">Thank you!</h2>
                            <p className="text-sm text-gray-500 mt-2 max-w-xs">
                                Your feedback helps improve loan predictions for millions of Indians.
                            </p>
                        </div>

                        <button
                            id="download-pdf"
                            onClick={downloadPDF}
                            className="btn-primary flex items-center gap-2"
                        >
                            <Download size={18} />
                            Download PDF Report
                        </button>

                        <button
                            onClick={() => navigate('/')}
                            className="text-sm text-gray-400 hover:text-gold transition-colors"
                        >
                            ← Back to Home
                        </button>
                    </div>
                )}
            </main>
        </div>
    )
}
